[build-system]
requires = ["setuptools>=80.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shapes"
version = "0.0.1"
description = "Geometry shapes area calculator"
readme = "README.md"
requires-python = ">=3.7"
dependencies = []